CREATE TABLE [fdp].[KNVP] (
    [MANDT] NVARCHAR (3)  NOT NULL,
    [KUNNR] NVARCHAR (10) NOT NULL,
    [VKORG] NVARCHAR (4)  NOT NULL,
    [VTWEG] NVARCHAR (2)  NOT NULL,
    [SPART] NVARCHAR (2)  NOT NULL,
    [PARVW] NVARCHAR (2)  NOT NULL,
    [PARZA] NVARCHAR (3)  NOT NULL,
    [KUNN2] NVARCHAR (10) NOT NULL,
    [LIFNR] NVARCHAR (10) NOT NULL,
    [PERNR] NVARCHAR (8)  NOT NULL,
    [PARNR] NVARCHAR (10) NOT NULL,
    [KNREF] NVARCHAR (30) NOT NULL,
    [DEFPA] NVARCHAR (1)  NOT NULL
);

