CREATE TABLE [fdp].[MAKT] (
    [MANDT] NVARCHAR (3)  NOT NULL,
    [MATNR] NVARCHAR (18) NOT NULL,
    [SPRAS] NVARCHAR (1)  NOT NULL,
    [MAKTX] NVARCHAR (40) NOT NULL,
    [MAKTG] NVARCHAR (40) NOT NULL
);

