CREATE TABLE [fdp].[VBAP] (
    [MANDT]                 NVARCHAR (3)    NOT NULL,
    [VBELN]                 NVARCHAR (10)   NOT NULL,
    [POSNR]                 NVARCHAR (6)    NOT NULL,
    [MATNR]                 NVARCHAR (18)   NOT NULL,
    [MATWA]                 NVARCHAR (18)   NOT NULL,
    [PMATN]                 NVARCHAR (18)   NOT NULL,
    [CHARG]                 NVARCHAR (10)   NOT NULL,
    [MATKL]                 NVARCHAR (9)    NOT NULL,
    [ARKTX]                 NVARCHAR (40)   NOT NULL,
    [PSTYV]                 NVARCHAR (4)    NOT NULL,
    [POSAR]                 NVARCHAR (1)    NOT NULL,
    [LFREL]                 NVARCHAR (1)    NOT NULL,
    [FKREL]                 NVARCHAR (1)    NOT NULL,
    [UEPOS]                 NVARCHAR (6)    NOT NULL,
    [GRPOS]                 NVARCHAR (6)    NOT NULL,
    [ABGRU]                 NVARCHAR (2)    NOT NULL,
    [PRODH]                 NVARCHAR (18)   NOT NULL,
    [ZWERT]                 NUMERIC (13, 2) NOT NULL,
    [ZMENG]                 NUMERIC (13, 3) NOT NULL,
    [ZIEME]                 NVARCHAR (3)    NOT NULL,
    [UMZIZ]                 NUMERIC (5)     NOT NULL,
    [UMZIN]                 NUMERIC (5)     NOT NULL,
    [MEINS]                 NVARCHAR (3)    NOT NULL,
    [SMENG]                 NUMERIC (13, 3) NOT NULL,
    [ABLFZ]                 NUMERIC (13, 3) NOT NULL,
    [ABDAT]                 NVARCHAR (8)    NOT NULL,
    [ABSFZ]                 NUMERIC (13, 3) NOT NULL,
    [POSEX]                 NVARCHAR (6)    NOT NULL,
    [KDMAT]                 NVARCHAR (35)   NOT NULL,
    [KBVER]                 NUMERIC (3)     NOT NULL,
    [KEVER]                 NUMERIC (3)     NOT NULL,
    [VKGRU]                 NVARCHAR (3)    NOT NULL,
    [VKAUS]                 NVARCHAR (3)    NOT NULL,
    [GRKOR]                 NVARCHAR (3)    NOT NULL,
    [FMENG]                 NVARCHAR (1)    NOT NULL,
    [UEBTK]                 NVARCHAR (1)    NOT NULL,
    [UEBTO]                 NUMERIC (3, 1)  NOT NULL,
    [UNTTO]                 NUMERIC (3, 1)  NOT NULL,
    [FAKSP]                 NVARCHAR (2)    NOT NULL,
    [ATPKZ]                 NVARCHAR (1)    NOT NULL,
    [RKFKF]                 NVARCHAR (1)    NOT NULL,
    [SPART]                 NVARCHAR (2)    NOT NULL,
    [GSBER]                 NVARCHAR (4)    NOT NULL,
    [NETWR]                 NUMERIC (15, 2) NOT NULL,
    [WAERK]                 NVARCHAR (5)    NOT NULL,
    [ANTLF]                 NUMERIC (1)     NOT NULL,
    [KZTLF]                 NVARCHAR (1)    NOT NULL,
    [CHSPL]                 NVARCHAR (1)    NOT NULL,
    [KWMENG]                NUMERIC (15, 3) NOT NULL,
    [LSMENG]                NUMERIC (15, 3) NOT NULL,
    [KBMENG]                NUMERIC (15, 3) NOT NULL,
    [KLMENG]                NUMERIC (15, 3) NOT NULL,
    [VRKME]                 NVARCHAR (3)    NOT NULL,
    [UMVKZ]                 NUMERIC (5)     NOT NULL,
    [UMVKN]                 NUMERIC (5)     NOT NULL,
    [BRGEW]                 NUMERIC (15, 3) NOT NULL,
    [NTGEW]                 NUMERIC (15, 3) NOT NULL,
    [GEWEI]                 NVARCHAR (3)    NOT NULL,
    [VOLUM]                 NUMERIC (15, 3) NOT NULL,
    [VOLEH]                 NVARCHAR (3)    NOT NULL,
    [VBELV]                 NVARCHAR (10)   NOT NULL,
    [POSNV]                 NVARCHAR (6)    NOT NULL,
    [VGBEL]                 NVARCHAR (10)   NOT NULL,
    [VGPOS]                 NVARCHAR (6)    NOT NULL,
    [VOREF]                 NVARCHAR (1)    NOT NULL,
    [UPFLU]                 NVARCHAR (1)    NOT NULL,
    [ERLRE]                 NVARCHAR (1)    NOT NULL,
    [LPRIO]                 NVARCHAR (2)    NOT NULL,
    [WERKS]                 NVARCHAR (4)    NOT NULL,
    [LGORT]                 NVARCHAR (4)    NOT NULL,
    [VSTEL]                 NVARCHAR (4)    NOT NULL,
    [ROUTE]                 NVARCHAR (6)    NOT NULL,
    [STKEY]                 NVARCHAR (1)    NOT NULL,
    [STDAT]                 NVARCHAR (8)    NOT NULL,
    [STLNR]                 NVARCHAR (8)    NOT NULL,
    [STPOS]                 NUMERIC (5)     NOT NULL,
    [AWAHR]                 NVARCHAR (3)    NOT NULL,
    [ERDAT]                 NVARCHAR (8)    NOT NULL,
    [ERNAM]                 NVARCHAR (12)   NOT NULL,
    [ERZET]                 NVARCHAR (6)    NOT NULL,
    [TAXM1]                 NVARCHAR (1)    NOT NULL,
    [TAXM2]                 NVARCHAR (1)    NOT NULL,
    [TAXM3]                 NVARCHAR (1)    NOT NULL,
    [TAXM4]                 NVARCHAR (1)    NOT NULL,
    [TAXM5]                 NVARCHAR (1)    NOT NULL,
    [TAXM6]                 NVARCHAR (1)    NOT NULL,
    [TAXM7]                 NVARCHAR (1)    NOT NULL,
    [TAXM8]                 NVARCHAR (1)    NOT NULL,
    [TAXM9]                 NVARCHAR (1)    NOT NULL,
    [VBEAF]                 NUMERIC (5, 2)  NOT NULL,
    [VBEAV]                 NUMERIC (5, 2)  NOT NULL,
    [VGREF]                 NVARCHAR (1)    NOT NULL,
    [NETPR]                 NUMERIC (11, 2) NOT NULL,
    [KPEIN]                 NUMERIC (5)     NOT NULL,
    [KMEIN]                 NVARCHAR (3)    NOT NULL,
    [SHKZG]                 NVARCHAR (1)    NOT NULL,
    [SKTOF]                 NVARCHAR (1)    NOT NULL,
    [MTVFP]                 NVARCHAR (2)    NOT NULL,
    [SUMBD]                 NVARCHAR (1)    NOT NULL,
    [KONDM]                 NVARCHAR (2)    NOT NULL,
    [KTGRM]                 NVARCHAR (2)    NOT NULL,
    [BONUS]                 NVARCHAR (2)    NOT NULL,
    [PROVG]                 NVARCHAR (2)    NOT NULL,
    [EANNR]                 NVARCHAR (13)   NOT NULL,
    [PRSOK]                 NVARCHAR (1)    NOT NULL,
    [BWTAR]                 NVARCHAR (10)   NOT NULL,
    [BWTEX]                 NVARCHAR (1)    NOT NULL,
    [XCHPF]                 NVARCHAR (1)    NOT NULL,
    [XCHAR]                 NVARCHAR (1)    NOT NULL,
    [LFMNG]                 NUMERIC (13, 3) NOT NULL,
    [STAFO]                 NVARCHAR (6)    NOT NULL,
    [WAVWR]                 NUMERIC (13, 2) NOT NULL,
    [KZWI1]                 NUMERIC (13, 2) NOT NULL,
    [KZWI2]                 NUMERIC (13, 2) NOT NULL,
    [KZWI3]                 NUMERIC (13, 2) NOT NULL,
    [KZWI4]                 NUMERIC (13, 2) NOT NULL,
    [KZWI5]                 NUMERIC (13, 2) NOT NULL,
    [KZWI6]                 NUMERIC (13, 2) NOT NULL,
    [STCUR]                 NUMERIC (9, 5)  NOT NULL,
    [AEDAT]                 NVARCHAR (8)    NOT NULL,
    [EAN11]                 NVARCHAR (18)   NOT NULL,
    [FIXMG]                 NVARCHAR (1)    NOT NULL,
    [PRCTR]                 NVARCHAR (10)   NOT NULL,
    [MVGR1]                 NVARCHAR (3)    NOT NULL,
    [MVGR2]                 NVARCHAR (3)    NOT NULL,
    [MVGR3]                 NVARCHAR (3)    NOT NULL,
    [MVGR4]                 NVARCHAR (3)    NOT NULL,
    [MVGR5]                 NVARCHAR (3)    NOT NULL,
    [KMPMG]                 NUMERIC (13, 3) NOT NULL,
    [SUGRD]                 NVARCHAR (4)    NOT NULL,
    [SOBKZ]                 NVARCHAR (1)    NOT NULL,
    [VPZUO]                 NVARCHAR (1)    NOT NULL,
    [PAOBJNR]               NVARCHAR (10)   NOT NULL,
    [PS_PSP_PNR]            NVARCHAR (8)    NOT NULL,
    [AUFNR]                 NVARCHAR (12)   NOT NULL,
    [VPMAT]                 NVARCHAR (18)   NOT NULL,
    [VPWRK]                 NVARCHAR (4)    NOT NULL,
    [PRBME]                 NVARCHAR (3)    NOT NULL,
    [UMREF]                 FLOAT (53)      NOT NULL,
    [KNTTP]                 NVARCHAR (1)    NOT NULL,
    [KZVBR]                 NVARCHAR (1)    NOT NULL,
    [SERNR]                 NVARCHAR (8)    NOT NULL,
    [OBJNR]                 NVARCHAR (22)   NOT NULL,
    [ABGRS]                 NVARCHAR (6)    NOT NULL,
    [BEDAE]                 NVARCHAR (4)    NOT NULL,
    [CMPRE]                 NUMERIC (11, 2) NOT NULL,
    [CMTFG]                 NVARCHAR (1)    NOT NULL,
    [CMPNT]                 NVARCHAR (1)    NOT NULL,
    [CMKUA]                 NUMERIC (9, 5)  NOT NULL,
    [CUOBJ]                 NVARCHAR (18)   NOT NULL,
    [CUOBJ_CH]              NVARCHAR (18)   NOT NULL,
    [CEPOK]                 NVARCHAR (1)    NOT NULL,
    [KOUPD]                 NVARCHAR (1)    NOT NULL,
    [SERAIL]                NVARCHAR (4)    NOT NULL,
    [ANZSN]                 INT             NOT NULL,
    [NACHL]                 NVARCHAR (1)    NOT NULL,
    [MAGRV]                 NVARCHAR (4)    NOT NULL,
    [MPROK]                 NVARCHAR (1)    NOT NULL,
    [VGTYP]                 NVARCHAR (1)    NOT NULL,
    [PROSA]                 NVARCHAR (1)    NOT NULL,
    [UEPVW]                 NVARCHAR (1)    NOT NULL,
    [KALNR]                 NVARCHAR (12)   NOT NULL,
    [KLVAR]                 NVARCHAR (4)    NOT NULL,
    [SPOSN]                 NVARCHAR (4)    NOT NULL,
    [KOWRR]                 NVARCHAR (1)    NOT NULL,
    [STADAT]                NVARCHAR (8)    NOT NULL,
    [EXART]                 NVARCHAR (2)    NOT NULL,
    [PREFE]                 NVARCHAR (1)    NOT NULL,
    [KNUMH]                 NVARCHAR (10)   NOT NULL,
    [CLINT]                 NVARCHAR (10)   NOT NULL,
    [CHMVS]                 NVARCHAR (3)    NOT NULL,
    [STLTY]                 NVARCHAR (1)    NOT NULL,
    [STLKN]                 NVARCHAR (8)    NOT NULL,
    [STPOZ]                 NVARCHAR (8)    NOT NULL,
    [STMAN]                 NVARCHAR (1)    NOT NULL,
    [ZSCHL_K]               NVARCHAR (6)    NOT NULL,
    [KALSM_K]               NVARCHAR (6)    NOT NULL,
    [KALVAR]                NVARCHAR (4)    NOT NULL,
    [KOSCH]                 NVARCHAR (18)   NOT NULL,
    [UPMAT]                 NVARCHAR (18)   NOT NULL,
    [UKONM]                 NVARCHAR (2)    NOT NULL,
    [MFRGR]                 NVARCHAR (8)    NOT NULL,
    [PLAVO]                 NVARCHAR (4)    NOT NULL,
    [KANNR]                 NVARCHAR (35)   NOT NULL,
    [CMPRE_FLT]             FLOAT (53)      NOT NULL,
    [ABFOR]                 NVARCHAR (2)    NOT NULL,
    [ABGES]                 FLOAT (53)      NOT NULL,
    [J_1BCFOP]              NVARCHAR (10)   NOT NULL,
    [J_1BTAXLW1]            NVARCHAR (3)    NOT NULL,
    [J_1BTAXLW2]            NVARCHAR (3)    NOT NULL,
    [J_1BTXSDC]             NVARCHAR (2)    NOT NULL,
    [WKTNR]                 NVARCHAR (10)   NOT NULL,
    [WKTPS]                 NVARCHAR (6)    NOT NULL,
    [SKOPF]                 NVARCHAR (18)   NOT NULL,
    [KZBWS]                 NVARCHAR (1)    NOT NULL,
    [WGRU1]                 NVARCHAR (18)   NOT NULL,
    [WGRU2]                 NVARCHAR (18)   NOT NULL,
    [KNUMA_PI]              NVARCHAR (10)   NOT NULL,
    [KNUMA_AG]              NVARCHAR (10)   NOT NULL,
    [KZFME]                 NVARCHAR (1)    NOT NULL,
    [LSTANR]                NVARCHAR (1)    NOT NULL,
    [TECHS]                 NVARCHAR (12)   NOT NULL,
    [MWSBP]                 NUMERIC (13, 2) NOT NULL,
    [BERID]                 NVARCHAR (10)   NOT NULL,
    [PCTRF]                 NVARCHAR (10)   NOT NULL,
    [LOGSYS_EXT]            NVARCHAR (10)   NOT NULL,
    [J_1BTAXLW3]            NVARCHAR (3)    NOT NULL,
    [J_1BTAXLW4]            NVARCHAR (3)    NOT NULL,
    [J_1BTAXLW5]            NVARCHAR (3)    NOT NULL,
    [/BEV1/SRFUND]          NVARCHAR (2)    NOT NULL,
    [FERC_IND]              NVARCHAR (4)    NOT NULL,
    [KOSTL]                 NVARCHAR (10)   NOT NULL,
    [FONDS]                 NVARCHAR (10)   NOT NULL,
    [FISTL]                 NVARCHAR (16)   NOT NULL,
    [FKBER]                 NVARCHAR (16)   NOT NULL,
    [GRANT_NBR]             NVARCHAR (20)   NOT NULL,
    [STOCKLOC]              NVARCHAR (20)   NULL,
    [SLOCTYPE]              NVARCHAR (4)    NULL,
    [MSR_RET_REASON]        NVARCHAR (3)    NULL,
    [MSR_REFUND_CODE]       NVARCHAR (3)    NULL,
    [MSR_APPROV_BLOCK]      NVARCHAR (1)    NULL,
    [AUFPL_OLC]             NVARCHAR (10)   NULL,
    [APLZL_OLC]             NVARCHAR (8)    NULL,
    [IUID_RELEVANT]         NVARCHAR (1)    NULL,
    [PRS_OBJNR]             NVARCHAR (22)   NULL,
    [PARGB]                 NVARCHAR (4)    NULL,
    [ZZUCUE]                NVARCHAR (6)    NULL,
    [ZZTIPART]              NVARCHAR (2)    NULL,
    [NRAB_KNUMH]            NVARCHAR (10)   NULL,
    [TRMRISK_RELEVANT]      NVARCHAR (2)    NULL,
    [SGT_RCAT]              NVARCHAR (16)   NULL,
    [HANDOVERLOC]           NVARCHAR (10)   NULL,
    [HANDOVERDATE]          NVARCHAR (8)    NULL,
    [HANDOVERTIME]          NVARCHAR (6)    NULL,
    [TC_AUT_DET]            NVARCHAR (2)    NULL,
    [MANUAL_TC_REASON]      NVARCHAR (2)    NULL,
    [FISCAL_INCENTIVE]      NVARCHAR (4)    NULL,
    [TAX_SUBJECT_ST]        NVARCHAR (1)    NULL,
    [FISCAL_INCENTIVE_ID]   NVARCHAR (4)    NULL,
    [SPCSTO]                NVARCHAR (2)    NULL,
    [REVACC_REFID]          NVARCHAR (30)   NULL,
    [REVACC_REFTYPE]        NVARCHAR (3)    NULL,
    [PRS_SD_SPSNR]          NVARCHAR (8)    NULL,
    [PRS_WORK_PERIOD]       NVARCHAR (7)    NULL,
    [AUFPL_OAA]             NVARCHAR (10)   NULL,
    [APLZL_OAA]             NVARCHAR (8)    NULL,
    [SESSION_CREATION_DATE] NVARCHAR (8)    NULL,
    [SESSION_CREATION_TIME] NVARCHAR (6)    NULL
);

