CREATE TABLE [fdp].[ZFDG_KONV] (
    [MANDT] NVARCHAR (3)    NOT NULL,
    [KNUMV] NVARCHAR (10)   NOT NULL,
    [KPOSN] NVARCHAR (6)    NOT NULL,
    [STUNR] NVARCHAR (3)    NOT NULL,
    [ZAEHK] NVARCHAR (2)    NOT NULL,
    [KSCHL] NVARCHAR (4)    NOT NULL,
    [KBETR] NUMERIC (11, 2) NOT NULL,
    [WAERS] NVARCHAR (5)    NOT NULL,
    [SAKN1] NVARCHAR (10)   NOT NULL,
    [KVSL1] NVARCHAR (3)    NOT NULL,
    [KWERT] NUMERIC (13, 2) NOT NULL,
    [KDATU] NVARCHAR (8)    NOT NULL,
    [KNUMH] NVARCHAR (10)   NULL,
    [KHERK] NVARCHAR (1)    NULL,
    [KSTEU] NVARCHAR (1)    NULL,
    [KMPRS] NVARCHAR (1)    NULL,
    [KINAK] NVARCHAR (1)    NULL
);

